# Data Cleaning: Merge Datasets
This notebook is a scaffold for our data.py script. It will pull dataframes from the other "cleaning" Jupyter notebooks and merge them.

In [22]:
import pandas as pd
import numpy as np
import scipy.stats as sci
import datetime

# Import cleaned csv files from cleaning notebooks - USE THIS SECTION WHEN FILLED IN

In [23]:
## uncomment when the scripts below are set up
# from [data_VAERS.py] import df_VAERS_filtered
# from [data_symptoms.py] import df_symptoms_reshaped
# from [data_vax.py] import df_vax

In [24]:
## make dataframes (uncomment)
# df_VAERS_cl = df_VAERS_filtered
# df_symptoms_cl = df_symptoms_reshape
# df_vax_cl = df_vax

## Read in cleaned csv files - WITH LOCAL DATA FILES, DO NOT USE IN FINAL SCRIPTS

In [25]:
# make dataframes
df_VAERS_cl = pd.read_csv('/home/ekmys/PycharmProjects/covid-19-vaccine-adverse-reactions/data/VAERSDATA_cleaned.csv')
df_symptoms_cl = pd.read_csv('/home/ekmys/PycharmProjects/covid-19-vaccine-adverse-reactions/data/VAERSSYMPTOMS_cleaned.csv')
df_vax_cl = pd.read_csv('/home/ekmys/PycharmProjects/covid-19-vaccine-adverse-reactions/data/VAERSVAX_cleaned.csv')

In [26]:
# view df_VAERS_cl
df_VAERS_cl.head()
df_vax_cl.head()
df_symptoms_cl.head()

,Unnamed: 0,VAERS_ID,symptom,symptom_version,symptom_dict
0,0,902418,Hypoaesthesia,24.0,"{'SYMPTOM1': 'Hypoaesthesia', 'SYMPTOMVERSION1..."
1,1,902440,Headache,23.1,"{'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}"
2,2,902446,Erythema,23.1,"{'SYMPTOM1': 'Erythema', 'SYMPTOMVERSION1': 23.1}"
3,3,902464,Dizziness,23.1,"{'SYMPTOM1': 'Dizziness', 'SYMPTOMVERSION1': 2..."
4,4,902465,Dysgeusia,23.1,"{'SYMPTOM1': 'Dysgeusia', 'SYMPTOMVERSION1': 2..."

# Drop Unnamed Columns - may not be necessary with importing dataframes from other scripts

In [27]:
# drop unnamed columns
df_VAERS_cl = df_VAERS_cl.drop('Unnamed: 0', axis=1)
df_symptoms_cl = df_symptoms_cl.drop('Unnamed: 0', axis=1)
df_vax_cl = df_vax_cl.drop('Unnamed: 0', axis=1)

In [28]:
df_vax_cl.head()

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,902418,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,LA,PFIZER-BIONTECH
1,902440,COVID19,PFIZER\BIONTECH,EH9899,1.0,SYR,LA,PFIZER-BIONTECH
2,902446,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,RA,PFIZER-BIONTECH
3,902464,COVID19,PFIZER\BIONTECH,EH9899,NaN,IM,LA,PFIZER-BIONTECH
4,902465,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,RA,PFIZER-BIONTECH

# Merge all 3 datasets together

In [29]:
print("Shape of df_VAERS_cl: ", df_VAERS_cl.shape)
print("Shape of df_symptoms_cl: ", df_symptoms_cl.shape)
print("Shape of df_vax_cl: ", df_vax_cl.shape)

Shape of df_VAERS_cl:  (855196, 25)
Shape of df_symptoms_cl:  (4259322, 4)
Shape of df_vax_cl:  (1071521, 8)

In [30]:
# merge df_symptoms_cl and df_VAERS_cl
df_merged_symptoms_VAERS = pd.merge(df_symptoms_cl, df_VAERS_cl, how='left', on='VAERS_ID')
print("Shape of df_merged_VAERS_vax: ", df_merged_symptoms_VAERS.shape)

Shape of df_merged_VAERS_vax:  (4259322, 28)

In [31]:
# merge df_vax_cl with previous merge
df_merged_ALL = pd.merge(df_merged_symptoms_VAERS, df_vax_cl, how='left', on='VAERS_ID')
print("Shape of df_merged_ALL: ", df_merged_ALL.shape)

Shape of df_merged_ALL:  (4595283, 35)

In [32]:
df_merged_ALL.head()

,VAERS_ID,symptom,symptom_version,symptom_dict,RECVDATE,STATE,AGE_YRS,SEX,RPT_DATE,DIED,...,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,902418,Hypoaesthesia,24.0,"{'SYMPTOM1': 'Hypoaesthesia', 'SYMPTOMVERSION1...",2020-12-15,NJ,56.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,LA,PFIZER-BIONTECH
1,902440,Headache,23.1,"{'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}",2020-12-15,AZ,35.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,SYR,LA,PFIZER-BIONTECH
2,902446,Erythema,23.1,"{'SYMPTOM1': 'Erythema', 'SYMPTOMVERSION1': 23.1}",2020-12-15,WV,55.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,RA,PFIZER-BIONTECH
3,902464,Dizziness,23.1,"{'SYMPTOM1': 'Dizziness', 'SYMPTOMVERSION1': 2...",2020-12-15,LA,42.0,M,NaN,N,...,N,N,Y,COVID19,PFIZER\BIONTECH,EH9899,NaN,IM,LA,PFIZER-BIONTECH
4,902465,Dysgeusia,23.1,"{'SYMPTOM1': 'Dysgeusia', 'SYMPTOMVERSION1': 2...",2020-12-15,AR,60.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,RA,PFIZER-BIONTECH

# Filter Datasets for only Pfizer and Moderna rows

In [33]:
# get indices of rows to drop
idx_to_drop = df_merged_ALL[(df_merged_ALL['VAX_MANU'] != 'PFIZER\\BIONTECH') & (df_merged_ALL['VAX_MANU'] != 'MODERNA')].index

# sanity check
print(idx_to_drop)
print("Number of non-Pfizer and non-Moderna rows: ", len(idx_to_drop))
print("Total current rows in merged dataframe: ", len(df_merged_ALL))

Index([   1096,    5148,    6387,    6685,    7097,    7151,    9736,    9737,
         10297,   11279,
       ...
       4594859, 4595074, 4595131, 4595169, 4595190, 4595202, 4595203, 4595211,
       4595239, 4595262],
      dtype='int64', length=380738)
Number of non-Pfizer and non-Moderna rows:  380738
Total current rows in merged dataframe:  4595283

In [34]:
# additional sanity check w/sample indices from above
print(df_merged_ALL.iloc[1096])
print(df_merged_ALL.iloc[4595074])

VAERS_ID                                                      904043
symptom                                          Injection site pain
symptom_version                                                 24.0
symptom_dict       {'SYMPTOM1': 'Injection site pain', 'SYMPTOMVE...
RECVDATE                                                  2020-12-19
STATE                                                             FL
AGE_YRS                                                         58.0
SEX                                                                F
RPT_DATE                                                         NaN
DIED                                                               N
DATEDIED                                                         NaN
L_THREAT                                                           N
ER_VISIT                                                           N
HOSPITAL                                                           N
HOSPDAYS                                                         NaN
X_STAY                                                             N
DISABLE                                                            N
RECOVD                                                             N
VAX_DATE                                                  2020-12-18
ONSET_DATE                                                2020-12-19
NUMDAYS                                                          1.0
V_ADMINBY                                                        PVT
V_FUNDBY                                                         UNK
FORM_VERS                                                        2.0
TODAYS_DATE                                               2020-12-19
BIRTH_DEFECT                                                       N
OFC_VISIT                                                          N
ER_ED_VISIT                                                        N
VAX_TYPE                                                     COVID19
VAX_MANU                                         UNKNOWNMANUFACTURER
VAX_LOT                                                       EH9899
VAX_DOSE_SERIES                                                  1.0
VAX_ROUTE                                                         IM
VAX_SITE                                                          RA
VAX_NAME                                                     Unknown
Name: 1096, dtype: object
VAERS_ID                                                     2773946
symptom                                      Injection site swelling
symptom_version                                                 27.0
symptom_dict       {'SYMPTOM5': 'Injection site swelling', 'SYMPT...
RECVDATE                                                  2024-06-17
STATE                                                             IN
AGE_YRS                                                         38.0
SEX                                                                M
RPT_DATE                                                         NaN
DIED                                                               N
DATEDIED                                                         NaN
L_THREAT                                                           N
ER_VISIT                                                           N
HOSPITAL                                                           N
HOSPDAYS                                                         NaN
X_STAY                                                             N
DISABLE                                                            N
RECOVD                                                             N
VAX_DATE                                                  2023-12-12
ONSET_DATE                                                2023-12-12
NUMDAYS                                                          0.0
V_ADMINBY                                                        PHM
V_FUNDBY                                                         UNK
FORM_VERS                                                        2.0
TODAYS_DATE                                               2023-12-13
BIRTH_DEFECT                                                       N
OFC_VISIT                                                          N
ER_ED_VISIT                                                        N
VAX_TYPE                                                     COVID19
VAX_MANU                                                     NOVAVAX
VAX_LOT                                                    5683MF012
VAX_DOSE_SERIES                                                  1.0
VAX_ROUTE                                                         IM
VAX_SITE                                                          LA
VAX_NAME                                                     NOVAVAX
Name: 4595074, dtype: object

In [35]:
# drop rows
df_all_filtered = df_merged_ALL.drop(idx_to_drop)

# sanity check
print(df_all_filtered.head(10))
print("Shape of df_merged_ALL: ", df_merged_ALL.shape)
print("Shape of df_all_filtered: ", df_all_filtered.shape)
print(df_all_filtered['VAX_MANU'].unique().tolist()) # verify only Pfizer & Moderna rows remaining

   VAERS_ID              symptom  symptom_version  \
0    902418        Hypoaesthesia             24.0
1    902440             Headache             23.1
2    902446             Erythema             23.1
3    902464            Dizziness             23.1
4    902465            Dysgeusia             23.1
5    902465  Sensory disturbance             23.1
6    902468     Chest discomfort             24.0
7    902468             Dyspnoea             24.0
8    902479           Chest pain             23.1
9    902490             Headache             23.1

                                        symptom_dict    RECVDATE STATE  \
0  {'SYMPTOM1': 'Hypoaesthesia', 'SYMPTOMVERSION1...  2020-12-15    NJ
1  {'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}  2020-12-15    AZ
2  {'SYMPTOM1': 'Erythema', 'SYMPTOMVERSION1': 23.1}  2020-12-15    WV
3  {'SYMPTOM1': 'Dizziness', 'SYMPTOMVERSION1': 2...  2020-12-15    LA
4  {'SYMPTOM1': 'Dysgeusia', 'SYMPTOMVERSION1': 2...  2020-12-15    AR
5  {'SYMPTOM1': 'Sensory disturbance', 'SYMPTOMVE...  2020-12-15    AR
6  {'SYMPTOM1': 'Chest discomfort', 'SYMPTOMVERSI...  2020-12-15   NaN
7  {'SYMPTOM1': 'Dyspnoea', 'SYMPTOMVERSION1': 24.0}  2020-12-15   NaN
8  {'SYMPTOM1': 'Chest pain', 'SYMPTOMVERSION1': ...  2020-12-15    KS
9  {'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}  2020-12-15    NM

   AGE_YRS SEX RPT_DATE DIED  ... BIRTH_DEFECT OFC_VISIT ER_ED_VISIT VAX_TYPE  \
0     56.0   F      NaN    N  ...            N         N           N  COVID19
1     35.0   F      NaN    N  ...            N         N           N  COVID19
2     55.0   F      NaN    N  ...            N         N           N  COVID19
3     42.0   M      NaN    N  ...            N         N           Y  COVID19
4     60.0   F      NaN    N  ...            N         N           N  COVID19
5     60.0   F      NaN    N  ...            N         N           N  COVID19
6     59.0   M      NaN    N  ...            N         N           Y  COVID19
7     59.0   M      NaN    N  ...            N         N           Y  COVID19
8     46.0   F      NaN    N  ...            N         N           N  COVID19
9     37.0   F      NaN    N  ...            N         N           N  COVID19

          VAX_MANU VAX_LOT VAX_DOSE_SERIES VAX_ROUTE VAX_SITE         VAX_NAME
0  PFIZER\BIONTECH  EH9899             1.0        IM       LA  PFIZER-BIONTECH
1  PFIZER\BIONTECH  EH9899             1.0       SYR       LA  PFIZER-BIONTECH
2  PFIZER\BIONTECH  EH9899             1.0        IM       RA  PFIZER-BIONTECH
3  PFIZER\BIONTECH  EH9899             NaN        IM       LA  PFIZER-BIONTECH
4  PFIZER\BIONTECH  EH9899             1.0        IM       RA  PFIZER-BIONTECH
5  PFIZER\BIONTECH  EH9899             1.0        IM       RA  PFIZER-BIONTECH
6  PFIZER\BIONTECH  EH9899             1.0        IM       LA  PFIZER-BIONTECH
7  PFIZER\BIONTECH  EH9899             1.0        IM       LA  PFIZER-BIONTECH
8  PFIZER\BIONTECH     NaN             1.0        IM       LA  PFIZER-BIONTECH
9  PFIZER\BIONTECH  EH9899             1.0        IM       LA  PFIZER-BIONTECH

[10 rows x 35 columns]
Shape of df_merged_ALL:  (4595283, 35)
Shape of df_all_filtered:  (4214545, 35)
['PFIZER\\BIONTECH', 'MODERNA']

In [ ]:
# write filtered dataframe to csv file in same place as kaggle stuff was saved on local disk
# df_all_filtered.to_csv("data/alldata_filtered.csv") (not sure if this needs to be in the kaggle folder or elsewhere)