# Data Cleaning: Merge Datasets
This notebook is a scaffold for our data.py script. It will pull dataframes from the other "cleaning" Jupyter notebooks and merge them.

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as sci
import datetime

# Import cleaned csv files from cleaning notebooks - USE THIS SECTION WHEN FILLED IN

In [2]:
## uncomment when the scripts below are set up
# from [data_VAERS.py] import df_VAERS_filtered
# from [data_symptoms.py] import df_symptoms_reshaped
# from [data_vax.py] import df_vax

In [3]:
## make dataframes (uncomment)
# df_VAERS_cl = df_VAERS_filtered
# df_symptoms_cl = df_symptoms_reshape
# df_vax_cl = df_vax

## Read in cleaned csv files - WITH LOCAL DATA FILES, DO NOT USE IN FINAL SCRIPTS

In [2]:
# make dataframes
df_VAERS_cl = pd.read_csv('/home/ekmys/PycharmProjects/covid-19-vaccine-adverse-reactions/data/VAERSDATA_cleaned.csv')
df_symptoms_cl = pd.read_csv('/home/ekmys/PycharmProjects/covid-19-vaccine-adverse-reactions/data/VAERSSYMPTOMS_cleaned.csv')
df_vax_cl = pd.read_csv('/home/ekmys/PycharmProjects/covid-19-vaccine-adverse-reactions/data/VAERSVAX_cleaned.csv')

In [3]:
# view df_VAERS_cl
df_VAERS_cl.head()
df_vax_cl.head()
df_symptoms_cl.head()

,Unnamed: 0,VAERS_ID,symptom,symptom_version,symptom_dict
0,0,902418,Hypoaesthesia,24.0,"{'SYMPTOM1': 'Hypoaesthesia', 'SYMPTOMVERSION1..."
1,1,902440,Headache,23.1,"{'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}"
2,2,902446,Erythema,23.1,"{'SYMPTOM1': 'Erythema', 'SYMPTOMVERSION1': 23.1}"
3,3,902464,Dizziness,23.1,"{'SYMPTOM1': 'Dizziness', 'SYMPTOMVERSION1': 2..."
4,4,902465,Dysgeusia,23.1,"{'SYMPTOM1': 'Dysgeusia', 'SYMPTOMVERSION1': 2..."

# Drop Unnamed Columns - may not be necessary with importing dataframes from other scripts

In [4]:
# drop unnamed columns
df_VAERS_cl = df_VAERS_cl.drop('Unnamed: 0', axis=1)
df_symptoms_cl = df_symptoms_cl.drop('Unnamed: 0', axis=1)
df_vax_cl = df_vax_cl.drop('Unnamed: 0', axis=1)

In [5]:
df_vax_cl.head()

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,902418,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,LA,PFIZER-BIONTECH
1,902440,COVID19,PFIZER\BIONTECH,EH9899,1.0,SYR,LA,PFIZER-BIONTECH
2,902446,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,RA,PFIZER-BIONTECH
3,902464,COVID19,PFIZER\BIONTECH,EH9899,NaN,IM,LA,PFIZER-BIONTECH
4,902465,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,RA,PFIZER-BIONTECH

# Merge all 3 datasets together

In [6]:
print("Shape of df_VAERS_cl: ", df_VAERS_cl.shape)
print("Shape of df_symptoms_cl: ", df_symptoms_cl.shape)
print("Shape of df_vax_cl: ", df_vax_cl.shape)

Shape of df_VAERS_cl:  (855196, 25)
Shape of df_symptoms_cl:  (4259322, 4)
Shape of df_vax_cl:  (1071521, 8)

In [7]:
# merge df_symptoms_cl and df_VAERS_cl
df_merged_symptoms_VAERS = pd.merge(df_symptoms_cl, df_VAERS_cl, how='left', on='VAERS_ID')
print("Shape of df_merged_VAERS_vax: ", df_merged_symptoms_VAERS.shape)

Shape of df_merged_VAERS_vax:  (4259322, 28)

In [8]:
# merge df_vax_cl with previous merge
df_merged_ALL = pd.merge(df_merged_symptoms_VAERS, df_vax_cl, how='left', on='VAERS_ID')
print("Shape of df_merged_ALL: ", df_merged_ALL.shape)

Shape of df_merged_ALL:  (4595283, 35)

In [9]:
df_merged_ALL.head()

,VAERS_ID,symptom,symptom_version,symptom_dict,RECVDATE,STATE,AGE_YRS,SEX,RPT_DATE,DIED,...,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,902418,Hypoaesthesia,24.0,"{'SYMPTOM1': 'Hypoaesthesia', 'SYMPTOMVERSION1...",2020-12-15,NJ,56.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,LA,PFIZER-BIONTECH
1,902440,Headache,23.1,"{'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}",2020-12-15,AZ,35.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,SYR,LA,PFIZER-BIONTECH
2,902446,Erythema,23.1,"{'SYMPTOM1': 'Erythema', 'SYMPTOMVERSION1': 23.1}",2020-12-15,WV,55.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,RA,PFIZER-BIONTECH
3,902464,Dizziness,23.1,"{'SYMPTOM1': 'Dizziness', 'SYMPTOMVERSION1': 2...",2020-12-15,LA,42.0,M,NaN,N,...,N,N,Y,COVID19,PFIZER\BIONTECH,EH9899,NaN,IM,LA,PFIZER-BIONTECH
4,902465,Dysgeusia,23.1,"{'SYMPTOM1': 'Dysgeusia', 'SYMPTOMVERSION1': 2...",2020-12-15,AR,60.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,RA,PFIZER-BIONTECH

# Filter Datasets for only Pfizer and Moderna rows

In [10]:
# get indices of rows to drop
idx_to_drop = df_merged_ALL[(df_merged_ALL['VAX_MANU'] != 'PFIZER\\BIONTECH') & (df_merged_ALL['VAX_MANU'] != 'MODERNA')].index

# sanity check
print(idx_to_drop)
print("Number of non-Pfizer and non-Moderna rows: ", len(idx_to_drop))
print("Total current rows in merged dataframe: ", len(df_merged_ALL))

Index([   1096,    5148,    6387,    6685,    7097,    7151,    9736,    9737,
         10297,   11279,
       ...
       4594859, 4595074, 4595131, 4595169, 4595190, 4595202, 4595203, 4595211,
       4595239, 4595262],
      dtype='int64', length=380738)
Number of non-Pfizer and non-Moderna rows:  380738
Total current rows in merged dataframe:  4595283

In [11]:
# additional sanity check w/sample indices from above
print(df_merged_ALL.iloc[1096])
print(df_merged_ALL.iloc[4595074])

VAERS_ID                                                      904043
symptom                                          Injection site pain
symptom_version                                                 24.0
symptom_dict       {'SYMPTOM1': 'Injection site pain', 'SYMPTOMVE...
RECVDATE                                                  2020-12-19
STATE                                                             FL
AGE_YRS                                                         58.0
SEX                                                                F
RPT_DATE                                                         NaN
DIED                                                               N
DATEDIED                                                         NaN
L_THREAT                                                           N
ER_VISIT                                                           N
HOSPITAL                                                           N
HOSPDAYS                                                         NaN
X_STAY                                                             N
DISABLE                                                            N
RECOVD                                                             N
VAX_DATE                                                  2020-12-18
ONSET_DATE                                                2020-12-19
NUMDAYS                                                          1.0
V_ADMINBY                                                        PVT
V_FUNDBY                                                         UNK
FORM_VERS                                                        2.0
TODAYS_DATE                                               2020-12-19
BIRTH_DEFECT                                                       N
OFC_VISIT                                                          N
ER_ED_VISIT                                                        N
VAX_TYPE                                                     COVID19
VAX_MANU                                         UNKNOWNMANUFACTURER
VAX_LOT                                                       EH9899
VAX_DOSE_SERIES                                                  1.0
VAX_ROUTE                                                         IM
VAX_SITE                                                          RA
VAX_NAME                                                     Unknown
Name: 1096, dtype: object
VAERS_ID                                                     2773946
symptom                                      Injection site swelling
symptom_version                                                 27.0
symptom_dict       {'SYMPTOM5': 'Injection site swelling', 'SYMPT...
RECVDATE                                                  2024-06-17
STATE                                                             IN
AGE_YRS                                                         38.0
SEX                                                                M
RPT_DATE                                                         NaN
DIED                                                               N
DATEDIED                                                         NaN
L_THREAT                                                           N
ER_VISIT                                                           N
HOSPITAL                                                           N
HOSPDAYS                                                         NaN
X_STAY                                                             N
DISABLE                                                            N
RECOVD                                                             N
VAX_DATE                                                  2023-12-12
ONSET_DATE                                                2023-12-12
NUMDAYS                                                          0.0
V_ADMINBY                                                        PHM
V_FUNDBY                                                         UNK
FORM_VERS                                                        2.0
TODAYS_DATE                                               2023-12-13
BIRTH_DEFECT                                                       N
OFC_VISIT                                                          N
ER_ED_VISIT                                                        N
VAX_TYPE                                                     COVID19
VAX_MANU                                                     NOVAVAX
VAX_LOT                                                    5683MF012
VAX_DOSE_SERIES                                                  1.0
VAX_ROUTE                                                         IM
VAX_SITE                                                          LA
VAX_NAME                                                     NOVAVAX
Name: 4595074, dtype: object

In [12]:
# drop rows
df_all_filtered = df_merged_ALL.drop(idx_to_drop)

# sanity check
print(df_all_filtered.head(10))
print("Shape of df_merged_ALL: ", df_merged_ALL.shape)
print("Shape of df_all_filtered: ", df_all_filtered.shape)
print(df_all_filtered['VAX_MANU'].unique().tolist()) # verify only Pfizer & Moderna rows remaining

   VAERS_ID              symptom  symptom_version  \
0    902418        Hypoaesthesia             24.0
1    902440             Headache             23.1
2    902446             Erythema             23.1
3    902464            Dizziness             23.1
4    902465            Dysgeusia             23.1
5    902465  Sensory disturbance             23.1
6    902468     Chest discomfort             24.0
7    902468             Dyspnoea             24.0
8    902479           Chest pain             23.1
9    902490             Headache             23.1

                                        symptom_dict    RECVDATE STATE  \
0  {'SYMPTOM1': 'Hypoaesthesia', 'SYMPTOMVERSION1...  2020-12-15    NJ
1  {'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}  2020-12-15    AZ
2  {'SYMPTOM1': 'Erythema', 'SYMPTOMVERSION1': 23.1}  2020-12-15    WV
3  {'SYMPTOM1': 'Dizziness', 'SYMPTOMVERSION1': 2...  2020-12-15    LA
4  {'SYMPTOM1': 'Dysgeusia', 'SYMPTOMVERSION1': 2...  2020-12-15    AR
5  {'SYMPTOM1': 'Sensory disturbance', 'SYMPTOMVE...  2020-12-15    AR
6  {'SYMPTOM1': 'Chest discomfort', 'SYMPTOMVERSI...  2020-12-15   NaN
7  {'SYMPTOM1': 'Dyspnoea', 'SYMPTOMVERSION1': 24.0}  2020-12-15   NaN
8  {'SYMPTOM1': 'Chest pain', 'SYMPTOMVERSION1': ...  2020-12-15    KS
9  {'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}  2020-12-15    NM

   AGE_YRS SEX RPT_DATE DIED  ... BIRTH_DEFECT OFC_VISIT ER_ED_VISIT VAX_TYPE  \
0     56.0   F      NaN    N  ...            N         N           N  COVID19
1     35.0   F      NaN    N  ...            N         N           N  COVID19
2     55.0   F      NaN    N  ...            N         N           N  COVID19
3     42.0   M      NaN    N  ...            N         N           Y  COVID19
4     60.0   F      NaN    N  ...            N         N           N  COVID19
5     60.0   F      NaN    N  ...            N         N           N  COVID19
6     59.0   M      NaN    N  ...            N         N           Y  COVID19
7     59.0   M      NaN    N  ...            N         N           Y  COVID19
8     46.0   F      NaN    N  ...            N         N           N  COVID19
9     37.0   F      NaN    N  ...            N         N           N  COVID19

          VAX_MANU VAX_LOT VAX_DOSE_SERIES VAX_ROUTE VAX_SITE         VAX_NAME
0  PFIZER\BIONTECH  EH9899             1.0        IM       LA  PFIZER-BIONTECH
1  PFIZER\BIONTECH  EH9899             1.0       SYR       LA  PFIZER-BIONTECH
2  PFIZER\BIONTECH  EH9899             1.0        IM       RA  PFIZER-BIONTECH
3  PFIZER\BIONTECH  EH9899             NaN        IM       LA  PFIZER-BIONTECH
4  PFIZER\BIONTECH  EH9899             1.0        IM       RA  PFIZER-BIONTECH
5  PFIZER\BIONTECH  EH9899             1.0        IM       RA  PFIZER-BIONTECH
6  PFIZER\BIONTECH  EH9899             1.0        IM       LA  PFIZER-BIONTECH
7  PFIZER\BIONTECH  EH9899             1.0        IM       LA  PFIZER-BIONTECH
8  PFIZER\BIONTECH     NaN             1.0        IM       LA  PFIZER-BIONTECH
9  PFIZER\BIONTECH  EH9899             1.0        IM       LA  PFIZER-BIONTECH

[10 rows x 35 columns]
Shape of df_merged_ALL:  (4595283, 35)
Shape of df_all_filtered:  (4214545, 35)
['PFIZER\\BIONTECH', 'MODERNA']

# Filter rows for only western states
West region (CA, OR, WA, NV, UT, ID, MT, WY, CO, NM, HW, AK, AZ)

In [17]:
df_all_filtered.head()

,VAERS_ID,symptom,symptom_version,symptom_dict,RECVDATE,STATE,AGE_YRS,SEX,RPT_DATE,DIED,...,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,902418,Hypoaesthesia,24.0,"{'SYMPTOM1': 'Hypoaesthesia', 'SYMPTOMVERSION1...",2020-12-15,NJ,56.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,LA,PFIZER-BIONTECH
1,902440,Headache,23.1,"{'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}",2020-12-15,AZ,35.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,SYR,LA,PFIZER-BIONTECH
2,902446,Erythema,23.1,"{'SYMPTOM1': 'Erythema', 'SYMPTOMVERSION1': 23.1}",2020-12-15,WV,55.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,RA,PFIZER-BIONTECH
3,902464,Dizziness,23.1,"{'SYMPTOM1': 'Dizziness', 'SYMPTOMVERSION1': 2...",2020-12-15,LA,42.0,M,NaN,N,...,N,N,Y,COVID19,PFIZER\BIONTECH,EH9899,NaN,IM,LA,PFIZER-BIONTECH
4,902465,Dysgeusia,23.1,"{'SYMPTOM1': 'Dysgeusia', 'SYMPTOMVERSION1': 2...",2020-12-15,AR,60.0,F,NaN,N,...,N,N,N,COVID19,PFIZER\BIONTECH,EH9899,1.0,IM,RA,PFIZER-BIONTECH

In [21]:
# get indices of rows to drop
idx_to_drop1 = df_all_filtered[(df_all_filtered['STATE'] != 'CA') &
                            (df_all_filtered['STATE'] != 'OR') &
                            (df_all_filtered['STATE'] != 'WA') &
                            (df_all_filtered['STATE'] != 'NV') &
                            (df_all_filtered['STATE'] != 'UT') &
                            (df_all_filtered['STATE'] != 'ID') &
                            (df_all_filtered['STATE'] != 'MT') &
                            (df_all_filtered['STATE'] != 'WY') &
                            (df_all_filtered['STATE'] != 'CO') &
                            (df_all_filtered['STATE'] != 'NM') &
                            (df_all_filtered['STATE'] != 'HW') &
                            (df_all_filtered['STATE'] != 'AK') &
                            (df_all_filtered['STATE'] != 'AZ')].index

In [28]:
print(idx_to_drop1[0:50])

Index([ 0,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 23, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 38, 39, 40, 42,
       45, 46, 47, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
      dtype='int64')

In [29]:
print(df_all_filtered.iloc[59])

VAERS_ID                                                      902755
symptom                                                     Headache
symptom_version                                                 23.1
symptom_dict       {'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}
RECVDATE                                                  2020-12-16
STATE                                                             VA
AGE_YRS                                                         32.0
SEX                                                                M
RPT_DATE                                                         NaN
DIED                                                               N
DATEDIED                                                         NaN
L_THREAT                                                           N
ER_VISIT                                                           N
HOSPITAL                                                           N
HOSPDAYS                                                         NaN
X_STAY                                                             N
DISABLE                                                            N
RECOVD                                                             N
VAX_DATE                                                  2020-12-16
ONSET_DATE                                                2020-12-16
NUMDAYS                                                          0.0
V_ADMINBY                                                        PVT
V_FUNDBY                                                         UNK
FORM_VERS                                                        2.0
TODAYS_DATE                                               2020-12-16
BIRTH_DEFECT                                                       N
OFC_VISIT                                                          N
ER_ED_VISIT                                                        N
VAX_TYPE                                                     COVID19
VAX_MANU                                             PFIZER\BIONTECH
VAX_LOT                                                       EJ6185
VAX_DOSE_SERIES                                                  1.0
VAX_ROUTE                                                        SYR
VAX_SITE                                                          LA
VAX_NAME                                             PFIZER-BIONTECH
Name: 59, dtype: object

In [30]:
# drop rows
df_west_filtered = df_all_filtered.drop(idx_to_drop1)

# sanity check
print(df_west_filtered.head(10))
print("Shape of df_all_filtered: ", df_all_filtered.shape)
print("Shape of df_west_filtered: ", df_west_filtered.shape)
print(df_west_filtered['STATE'].unique().tolist()) # verify only western states now remaining

    VAERS_ID                  symptom  symptom_version  \
1     902440                 Headache             23.1
9     902490                 Headache             23.1
21    902557     Blood glucose normal             23.1
22    902557            Hyperhidrosis             23.1
29    902648              Feeling hot             23.1
37    902667  Injection site erythema             23.1
41    902671                Dizziness             23.1
43    902673                   Nausea             23.1
44    902674                Dizziness             23.1
48    902720                  Fatigue             23.1

                                         symptom_dict    RECVDATE STATE  \
1   {'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}  2020-12-15    AZ
9   {'SYMPTOM1': 'Headache', 'SYMPTOMVERSION1': 23.1}  2020-12-15    NM
21  {'SYMPTOM1': 'Blood glucose normal', 'SYMPTOMV...  2020-12-15    AK
22  {'SYMPTOM1': 'Hyperhidrosis', 'SYMPTOMVERSION1...  2020-12-15    AK
29  {'SYMPTOM1': 'Feeling hot', 'SYMPTOMVERSION1':...  2020-12-16    CA
37  {'SYMPTOM1': 'Injection site erythema', 'SYMPT...  2020-12-16    CO
41  {'SYMPTOM1': 'Dizziness', 'SYMPTOMVERSION1': 2...  2020-12-16    CO
43    {'SYMPTOM1': 'Nausea', 'SYMPTOMVERSION1': 23.1}  2020-12-16    CO
44  {'SYMPTOM1': 'Dizziness', 'SYMPTOMVERSION1': 2...  2020-12-16    WY
48   {'SYMPTOM1': 'Fatigue', 'SYMPTOMVERSION1': 23.1}  2020-12-16    NM

    AGE_YRS SEX RPT_DATE DIED  ... BIRTH_DEFECT OFC_VISIT ER_ED_VISIT  \
1      35.0   F      NaN    N  ...            N         N           N
9      37.0   F      NaN    N  ...            N         N           N
21     32.0   F      NaN    N  ...            N         N           Y
22     32.0   F      NaN    N  ...            N         N           Y
29     26.0   F      NaN    N  ...            N         Y           N
37     44.0   F      NaN    N  ...            N         N           N
41     72.0   M      NaN    N  ...            N         N           N
43     38.0   F      NaN    N  ...            N         N           N
44     38.0   F      NaN    N  ...            N         N           N
48     50.0   M      NaN    N  ...            N         N           N

   VAX_TYPE         VAX_MANU VAX_LOT VAX_DOSE_SERIES VAX_ROUTE VAX_SITE  \
1   COVID19  PFIZER\BIONTECH  EH9899             1.0       SYR       LA
9   COVID19  PFIZER\BIONTECH  EH9899             1.0        IM       LA
21  COVID19  PFIZER\BIONTECH  EK5730             1.0        IM       RA
22  COVID19  PFIZER\BIONTECH  EK5730             1.0        IM       RA
29  COVID19  PFIZER\BIONTECH  EH9899             1.0        IM       RA
37  COVID19  PFIZER\BIONTECH  EH9899             NaN        IM       LA
41  COVID19  PFIZER\BIONTECH  EH9899             NaN        IM       LA
43  COVID19  PFIZER\BIONTECH  EH9899             NaN        IM       RA
44  COVID19  PFIZER\BIONTECH     NaN             1.0        IM       LA
48  COVID19  PFIZER\BIONTECH     NaN             NaN        UN       UN

           VAX_NAME
1   PFIZER-BIONTECH
9   PFIZER-BIONTECH
21  PFIZER-BIONTECH
22  PFIZER-BIONTECH
29  PFIZER-BIONTECH
37  PFIZER-BIONTECH
41  PFIZER-BIONTECH
43  PFIZER-BIONTECH
44  PFIZER-BIONTECH
48  PFIZER-BIONTECH

[10 rows x 35 columns]
Shape of df_all_filtered:  (4214545, 35)
Shape of df_west_filtered:  (690380, 35)
['AZ', 'NM', 'AK', 'CA', 'CO', 'WY', 'WA', 'ID', 'MT', 'NV', 'OR', 'UT']

# Remove additional unnecessary columns

In [32]:
df_west_filtered = df_west_filtered.drop(['symptom_dict', 'VAX_NAME', 'VAX_ROUTE', 'VAX_SITE', 'VAX_TYPE'], axis=1)

In [33]:
df_west_filtered.head()

,VAERS_ID,symptom,symptom_version,RECVDATE,STATE,AGE_YRS,SEX,RPT_DATE,DIED,DATEDIED,...,V_ADMINBY,V_FUNDBY,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES
1,902440,Headache,23.1,2020-12-15,AZ,35.0,F,NaN,N,NaN,...,PVT,UNK,2.0,2020-12-15,N,N,N,PFIZER\BIONTECH,EH9899,1.0
9,902490,Headache,23.1,2020-12-15,NM,37.0,F,NaN,N,NaN,...,PVT,UNK,2.0,2020-12-15,N,N,N,PFIZER\BIONTECH,EH9899,1.0
21,902557,Blood glucose normal,23.1,2020-12-15,AK,32.0,F,NaN,N,NaN,...,PVT,UNK,2.0,2020-12-15,N,N,Y,PFIZER\BIONTECH,EK5730,1.0
22,902557,Hyperhidrosis,23.1,2020-12-15,AK,32.0,F,NaN,N,NaN,...,PVT,UNK,2.0,2020-12-15,N,N,Y,PFIZER\BIONTECH,EK5730,1.0
29,902648,Feeling hot,23.1,2020-12-16,CA,26.0,F,NaN,N,NaN,...,PVT,UNK,2.0,2020-12-16,N,Y,N,PFIZER\BIONTECH,EH9899,1.0

# Remove least common symptoms

In [80]:
# get symptom counts
symptom_counts = df_west_filtered['symptom'].value_counts()
df_symptom_counts = symptom_counts.to_frame()
df_symptom_counts = df_symptom_counts.sort_values(by='count', ascending=True)
df_symptom_counts = df_symptom_counts.reset_index()
print(df_symptom_counts.shape)

(3408, 2)

In [81]:
df_symptom_counts.head()

                                             symptom  count
0                                       Opisthotonus      4
1                                   Sensory overload      4
2                                      Cardiac index      4
3                                Perfume sensitivity      4
4  Single photon emission computerised tomogram a...      4

In [82]:
# do outlier analysis
# IQR Functions for outliers - created these during lab_02_todo
def get_iqr_upper(x):
    return x.quantile(0.75)+(1.5*(x.quantile(0.75)-x.quantile(0.25)))

def get_iqr_lower(x):
    iqr_low = x.quantile(0.25)-(1.5*(x.quantile(0.75)-x.quantile(0.25)))
    if iqr_low < 0:
        return 0
    else:
        return iqr_low

In [83]:
# get lower IQR threshold
lower = get_iqr_lower(df_symptom_counts['count'])
upper = get_iqr_upper(df_symptom_counts['count'])
print(lower)
print(upper)

0
124.5

In [102]:
# Get symptoms where unique symptom count <= 3
symptom_counts1 = df_west_filtered['symptom'].value_counts()[df_west_filtered['symptom'].value_counts() <= 25]
print("Number of rows with 2 or fewer instances of a symptom: ", len(symptom_counts1))

Number of rows with 2 or fewer instances of a symptom:  144

In [103]:
# get least common symptoms to drop
df_symptom_counts1 = symptom_counts1.to_frame()
df_symptom_counts1 = df_symptom_counts1.sort_values(by='count', ascending=True)
df_symptom_counts1 = df_symptom_counts1.reset_index()
df_symptom_counts1.head()

                         symptom  count
0                       Delivery     21
1                  Protein urine     21
2  Blood triglycerides increased     21
3                     Pemphigoid     21
4                  Tongue biting     21

In [104]:
# get list of least common symptoms to drop
symptoms_to_drop = df_symptom_counts1['symptom'].to_list()
print(symptoms_to_drop)

['Delivery', 'Protein urine', 'Blood triglycerides increased', 'Pemphigoid', 'Tongue biting', 'Mean cell haemoglobin concentration decreased', 'Lipoma', 'Nerve conduction studies abnormal', 'Mean cell volume increased', 'Faeces soft', 'Protein total increased', 'Ultrasound kidney', 'Iron deficiency anaemia', 'Increased appetite', 'Cardiovascular disorder', 'Total lung capacity decreased', 'Immobile', 'Noninfective gingivitis', 'Type 1 diabetes mellitus', 'Appendicitis perforated', 'Injection site scab', 'Lower respiratory tract infection', 'Septic shock', 'White blood cells urine positive', 'Myasthenia gravis', 'Skin texture abnormal', 'Genital rash', 'Sleep deficit', 'Oxygen saturation normal', 'Respiratory tract irritation', 'Enterovirus test negative', 'Specialist consultation', 'Proctalgia', 'Reaction to previous exposure to any vaccine', 'Pneumonia aspiration', 'Venogram', 'Skin discomfort', 'Vitamin D deficiency', 'Epstein-Barr virus test negative', 'Cholecystectomy', 'Biopsy bone marrow', 'Blood immunoglobulin E', 'Hepatic steatosis', 'Staphylococcal infection', 'Injection site movement impairment', 'Blood cortisol', 'Gastroenteritis viral', 'Uterine leiomyoma', 'Glassy eyes', 'Foetal death', 'Varicella virus test negative', 'Epilepsy', 'Product label issue', 'Defaecation urgency', 'Albumin globulin ratio', 'Sleep study', 'Abdominal X-ray', 'Platelet transfusion', 'Visual acuity tests', 'Adenovirus test', 'Skin fissures', 'Impaired self-care', 'Eye contusion', 'Blood pressure systolic increased', 'Transaminases increased', 'Vaginal discharge', 'Nucleated red cells', 'Tongue blistering', 'Atrioventricular block', 'Oesophagogastroduodenoscopy', 'Urine odour abnormal', 'Cerebral thrombosis', 'Skin test positive', 'Ischaemia', "Meniere's disease", 'Mouth haemorrhage', 'Respiratory syncytial virus test', 'Blood chloride', 'Alopecia areata', 'Carditis', 'Dystonia', 'Nasal dryness', 'Urobilinogen urine', 'Stress echocardiogram', 'Urine ketone body absent', 'Blood potassium increased', 'Eyelid pain', 'Exercise electrocardiogram', 'Drug screen', 'Urine leukocyte esterase', 'Blood pressure systolic', 'Arteriogram coronary abnormal', 'Blood albumin', 'Polyuria', 'Vulval ulceration', 'Mastitis', 'Electrocardiogram ST segment abnormal', 'Tongue dry', 'Cardiac telemetry', 'Carbon dioxide', 'Tendon disorder', 'Peroneal nerve palsy', 'Pulseless electrical activity', 'Arthritis reactive', 'Magnetic resonance imaging brain abnormal', 'Ovarian cyst', 'Furuncle', 'Cerebral venous sinus thrombosis', 'Blood calcium increased', 'Joint effusion', 'Tachyphrenia', 'Electrophoresis protein', 'Urine ketone body present', 'Hospitalisation', 'Nerve conduction studies normal', 'Colonoscopy abnormal', 'Blood iron normal', 'Culture negative', 'Eosinophil count increased', 'Protein total', 'Liver disorder', 'Abdominal tenderness', 'Ultrasound thyroid', 'Drainage', 'N-terminal prohormone brain natriuretic peptide increased', 'Blood glucose fluctuation', 'Ventricular fibrillation', 'Haemorrhage urinary tract', 'Monocyte count decreased', 'Pharyngitis', 'Bilirubin urine', 'Sleep apnoea syndrome', 'Vascular pain', 'Hangover', 'Vaccination site vesicles', 'Hepatitis', 'Electrocardiogram T wave abnormal', 'Spinal osteoarthritis', 'Activated partial thromboplastin time shortened', 'Localised infection', 'Injection site indentation', 'Ligament sprain', 'Mean cell haemoglobin increased', 'Urine abnormality']

In [105]:
# get indices of least common symptoms to drop
idx_to_drop2 = df_west_filtered[(df_west_filtered['symptom'].isin(symptoms_to_drop))].index
print(len(idx_to_drop2))

3298

In [106]:
# drop rows with least common symptoms
df_west_filtered = df_west_filtered.drop(idx_to_drop2)
print(df_west_filtered.shape)

(664409, 30)

# Datetime Objects

In [114]:
# sanity check for datetime object type
print(type(df_west_filtered['ONSET_DATE'][1]))

<class 'str'>

In [115]:
## convert date objects in df_VAERS_filtered to datetime objects

# convert date columns to datetime objects
df_west_filtered['RECVDATE'] = df_west_filtered['RECVDATE'].astype('datetime64[ns]')
df_west_filtered['DATEDIED'] = df_west_filtered['DATEDIED'].astype('datetime64[ns]')
df_west_filtered['VAX_DATE'] = df_west_filtered['VAX_DATE'].astype('datetime64[ns]')
df_west_filtered['ONSET_DATE'] = df_west_filtered['ONSET_DATE'].astype('datetime64[ns]')
df_west_filtered['TODAYS_DATE'] = df_west_filtered['TODAYS_DATE'].astype('datetime64[ns]')
df_west_filtered['RPT_DATE'] = df_west_filtered['RPT_DATE'].astype('datetime64[ns]')

# verify conversion to datetime object
print(df_west_filtered['RECVDATE'].dtype)
print(df_west_filtered['DATEDIED'].dtype)
print(df_west_filtered['VAX_DATE'].dtype)
print(df_west_filtered['ONSET_DATE'].dtype)
print(df_west_filtered['TODAYS_DATE'].dtype)
print(df_west_filtered['RPT_DATE'].dtype)

datetime64[ns]
datetime64[ns]
datetime64[ns]
datetime64[ns]
datetime64[ns]
datetime64[ns]

In [116]:
# add Year, Month, and MonthYear columns
df_west_filtered['ONSET_YEAR'] = df_west_filtered['ONSET_DATE'].dt.year
df_west_filtered['ONSET_MONTH'] = df_west_filtered['ONSET_DATE'].dt.strftime('%b')
df_west_filtered['ONSET_MONTHYEAR'] = df_west_filtered['ONSET_DATE'].dt.strftime('%Y-%m')
df_west_filtered.head()

,VAERS_ID,symptom,symptom_version,RECVDATE,STATE,AGE_YRS,SEX,RPT_DATE,DIED,DATEDIED,...,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,ONSET_YEAR,ONSET_MONTH,ONSET_MONTHYEAR
1,902440,Headache,23.1,2020-12-15,AZ,35.0,F,NaT,N,NaT,...,2020-12-15,N,N,N,PFIZER\BIONTECH,EH9899,1.0,2020.0,Dec,2020-12
9,902490,Headache,23.1,2020-12-15,NM,37.0,F,NaT,N,NaT,...,2020-12-15,N,N,N,PFIZER\BIONTECH,EH9899,1.0,2020.0,Dec,2020-12
21,902557,Blood glucose normal,23.1,2020-12-15,AK,32.0,F,NaT,N,NaT,...,2020-12-15,N,N,Y,PFIZER\BIONTECH,EK5730,1.0,2020.0,Dec,2020-12
22,902557,Hyperhidrosis,23.1,2020-12-15,AK,32.0,F,NaT,N,NaT,...,2020-12-15,N,N,Y,PFIZER\BIONTECH,EK5730,1.0,2020.0,Dec,2020-12
29,902648,Feeling hot,23.1,2020-12-16,CA,26.0,F,NaT,N,NaT,...,2020-12-16,N,Y,N,PFIZER\BIONTECH,EH9899,1.0,2020.0,Dec,2020-12

# Drop EVEN MORE COLUMNS

In [120]:
df_west_filtered = df_west_filtered.drop(['symptom_version'], axis=1)

KeyError: "['symptom_version'] not found in axis"

In [121]:
df_west_filtered = df_west_filtered.drop(['BIRTH_DEFECT', 'OFC_VISIT', 'ER_ED_VISIT', 'ER_VISIT'], axis=1)

In [123]:
df_west_filtered = df_west_filtered.drop(['L_THREAT', 'X_STAY'], axis=1)

In [126]:
df_west_filtered = df_west_filtered.drop(['DATEDIED'], axis=1)

In [128]:
df_west_filtered = df_west_filtered.drop(['ONSET_MONTH'], axis=1)

In [130]:
df_west_filtered.head()

,VAERS_ID,symptom,RECVDATE,STATE,AGE_YRS,SEX,RPT_DATE,DIED,HOSPITAL,HOSPDAYS,...,NUMDAYS,V_ADMINBY,V_FUNDBY,FORM_VERS,TODAYS_DATE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,ONSET_YEAR,ONSET_MONTHYEAR
1,902440,Headache,2020-12-15,AZ,35.0,F,NaT,N,N,NaN,...,0.0,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EH9899,1.0,2020.0,2020-12
9,902490,Headache,2020-12-15,NM,37.0,F,NaT,N,N,NaN,...,0.0,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EH9899,1.0,2020.0,2020-12
21,902557,Blood glucose normal,2020-12-15,AK,32.0,F,NaT,N,N,NaN,...,0.0,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EK5730,1.0,2020.0,2020-12
22,902557,Hyperhidrosis,2020-12-15,AK,32.0,F,NaT,N,N,NaN,...,0.0,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EK5730,1.0,2020.0,2020-12
29,902648,Feeling hot,2020-12-16,CA,26.0,F,NaT,N,N,NaN,...,0.0,PVT,UNK,2.0,2020-12-16,PFIZER\BIONTECH,EH9899,1.0,2020.0,2020-12

# Write to CSV

In [129]:
# write western states dataframe to csv file
path = '/home/ekmys/.cache/kagglehub/datasets/ayushggarg/covid19-vaccine-adverse-reactions/versions/7'
path_to_save = path + '/west_states_filtered.csv'
path_to_save

df_west_filtered.to_csv(path_to_save)

# Test read_csv

In [132]:
test_df = pd.read_csv('/home/ekmys/PycharmProjects/covid-19-vaccine-adverse-reactions/data/west_states_filtered.csv')
test_df.head()

/tmp/ipykernel_9990/3392473433.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  test_df = pd.read_csv('/home/ekmys/PycharmProjects/covid-19-vaccine-adverse-reactions/data/west_states_filtered.csv')

,Unnamed: 0,VAERS_ID,symptom,RECVDATE,STATE,AGE_YRS,SEX,RPT_DATE,DIED,HOSPITAL,...,NUMDAYS,V_ADMINBY,V_FUNDBY,FORM_VERS,TODAYS_DATE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,ONSET_YEAR,ONSET_MONTHYEAR
0,1,902440,Headache,2020-12-15,AZ,35.0,F,NaN,N,N,...,0.0,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EH9899,1.0,2020.0,2020-12
1,9,902490,Headache,2020-12-15,NM,37.0,F,NaN,N,N,...,0.0,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EH9899,1.0,2020.0,2020-12
2,21,902557,Blood glucose normal,2020-12-15,AK,32.0,F,NaN,N,N,...,0.0,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EK5730,1.0,2020.0,2020-12
3,22,902557,Hyperhidrosis,2020-12-15,AK,32.0,F,NaN,N,N,...,0.0,PVT,UNK,2.0,2020-12-15,PFIZER\BIONTECH,EK5730,1.0,2020.0,2020-12
4,29,902648,Feeling hot,2020-12-16,CA,26.0,F,NaN,N,N,...,0.0,PVT,UNK,2.0,2020-12-16,PFIZER\BIONTECH,EH9899,1.0,2020.0,2020-12